# Generated by Django 4.2.2 on 2023-06-25 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipointegrante',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_integrantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipointegrante',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_creo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipointegrante',
            name='usuario_edito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_edito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_creo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario_edito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_edito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='equipointegrante',
            unique_together={('equipo', 'integrante')},
        ),
    ]
