# Generated by Django 4.2.2 on 2023-06-23 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField()),
                ('admin', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_integrantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo integrante',
                'verbose_name_plural': 'equipos integrantes',
                'unique_together': {('equipo', 'integrante')},
            },
        ),
    ]
