# Generated by Django 4.2.2 on 2023-06-26 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadisticas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_creo', to=settings.AUTH_USER_MODEL)),
                ('usuario_edito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_edito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catalogo de ejercicio',
                'verbose_name_plural': 'catalogos de ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_catalogo', to='ejercicios.catejercicio')),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_estadisticas', to='estadisticas.estadistica')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_creo', to=settings.AUTH_USER_MODEL)),
                ('usuario_edito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usuario_edito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
            },
        ),
    ]
